# Generated by Django 5.0.6 on 2024-06-16 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(blank=True, max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=25)),
                ('reason', models.TextField()),
                ('is_trash', models.BooleanField(blank=True, null=True)),
                ('qr_code', models.CharField(max_length=10)),
                ('time_in', models.BigIntegerField(null=True)),
                ('time_out', models.BigIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('trash_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user')),
            ],
            options={
                'db_table': 'trashes',
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_time_consumed', models.BigIntegerField(null=True)),
                ('total_visit', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user')),
            ],
            options={
                'db_table': 'sessionlogs',
            },
        ),
    ]
