# Generated by Django 5.0.6 on 2024-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_trash',
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='is_trash',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
