# Generated by Django 5.0.6 on 2024-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_user_qr_code_alter_user_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
