# Generated by Django 5.0.6 on 2024-06-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_user_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_in',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
