# Generated by Django 5.0.6 on 2024-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_user_time_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
