import type { Metadata } from "next";
import { Inter, Poppins, Open_Sans } from "next/font/google";
import { Toaster } from "sonner";
import Sidebar from "@/components/Sidebar";
import Provider from "./Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });
const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AttendanceHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <div className="w-full h-screen flex">
            <Sidebar />
            {children}
            <Toaster duration={2000} />
          </div>
        </Provider>
      </body>
    </html>
  );
}
